/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-21 06:58:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddDoctor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Form to add doctor and availability details -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<link rel=\"shortcut icon\" href=\"images/halomed2.png\">\r\n");
      out.write("	<title>HaloMed | Add Doctor and Availability Details</title>\r\n");
      out.write("	<link rel=\"shortcut icon\" href=\"images/halomed2.png\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/AddDoctor.css\">\r\n");
      out.write("	<script src=\"js/AddDoctor.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<h1>Enter Doctor and Availability Details</h1>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"form-container\">\r\n");
      out.write("	\r\n");
      out.write("		<!-- This form sends the doctor's details to AddDoctorServlet using POST method -->\r\n");
      out.write("		<form action=\"AddDoctorServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("	    	<table>\r\n");
      out.write("	        	<tr>\r\n");
      out.write("		            <td>Full Name:</td>\r\n");
      out.write("		            <td><input type=\"text\" name=\"full_name\" required></td>\r\n");
      out.write("	        	</tr>\r\n");
      out.write("	        	\r\n");
      out.write("		        <tr>\r\n");
      out.write("		            <td>Title:</td>\r\n");
      out.write("		            <td>\r\n");
      out.write("			            <select name=\"title\" style=\"width:100%;\" required>\r\n");
      out.write("			                <option value=\"Dr\">Dr</option>\r\n");
      out.write("			                <option value=\"Prof\">Prof</option>\r\n");
      out.write("			                <option value=\"Consult\">Consult</option>\r\n");
      out.write("			            </select>\r\n");
      out.write("		            </td>\r\n");
      out.write("		        </tr>\r\n");
      out.write("		        \r\n");
      out.write("		        <tr>\r\n");
      out.write("		        	<td>Specialization:</td>\r\n");
      out.write("		            <td>\r\n");
      out.write("					    <input list=\"specializations\" name=\"specialization\" required style=\"width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;\">\r\n");
      out.write("					    <datalist id=\"specializations\">\r\n");
      out.write("					        <option value=\"Physician\">\r\n");
      out.write("			            	<option value=\"Surgeon\">\r\n");
      out.write("			            	<option value=\"Psychologist\">\r\n");
      out.write("			                <option value=\"Cardiologist\">\r\n");
      out.write("			                <option value=\"Dermatologist\">\r\n");
      out.write("			                <option value=\"Neurologist\">\r\n");
      out.write("			                <option value=\"Pediatrician\">\r\n");
      out.write("			                <option value=\"Hematologist\">\r\n");
      out.write("			                <option value=\"Gastroenterologist\">	 \r\n");
      out.write("					    </datalist>\r\n");
      out.write("					</td>\r\n");
      out.write("		        </tr>\r\n");
      out.write("		        \r\n");
      out.write("		        <tr>\r\n");
      out.write("		            <td>Qualifications:</td>\r\n");
      out.write("		            <td><textarea name=\"qualifications\" rows=\"4\" style=\"width: 97%;\"  required></textarea></td>\r\n");
      out.write("	        	</tr>\r\n");
      out.write("	        	\r\n");
      out.write("		        <tr>\r\n");
      out.write("		            <td>Experience (years):</td>\r\n");
      out.write("		            <td><input type=\"number\" name=\"experience\" required></td>\r\n");
      out.write("		        </tr>\r\n");
      out.write("		        \r\n");
      out.write("		        <tr>\r\n");
      out.write("		            <td>Gender:</td>\r\n");
      out.write("		            <td>\r\n");
      out.write("			            <select name=\"gender\" class=\"large\" style=\"width: 100%;\" required>\r\n");
      out.write("			                <option value=\"Male\">Male</option>\r\n");
      out.write("			                <option value=\"Female\">Female</option>\r\n");
      out.write("			                <option value=\"Other\">Other</option>\r\n");
      out.write("			            </select>\r\n");
      out.write("		            </td>\r\n");
      out.write("	       	   </tr>\r\n");
      out.write("	       	   \r\n");
      out.write("		        <tr>\r\n");
      out.write("		            <td>Contact:</td>\r\n");
      out.write("		            <td><input type=\"text\" name=\"contact\" required></td>\r\n");
      out.write("		        </tr>\r\n");
      out.write("		        \r\n");
      out.write("		        <tr>\r\n");
      out.write("		            <td>Email:</td>\r\n");
      out.write("		            <td><input type=\"email\" name=\"email\" required></td>\r\n");
      out.write("		        </tr>\r\n");
      out.write("		        \r\n");
      out.write("		        <tr>\r\n");
      out.write("		            <td>Profile Photo:</td>\r\n");
      out.write("		            <td><input type=\"file\" name=\"profile_photo\" accept=\"image/*\" class=\"custom-file-input\" style=\"width: 97%;\"></td>\r\n");
      out.write("	        	</tr>\r\n");
      out.write("	        	\r\n");
      out.write("	    	</table>\r\n");
      out.write("	\r\n");
      out.write("	    	<div class=\"availability-section\">\r\n");
      out.write("	        	<h3>Availability Details</h3>\r\n");
      out.write("	        	\r\n");
      out.write("	        	<!-- This is the container where multiple availability entries can be added dynamically -->\r\n");
      out.write("	        	<div id=\"availabilityEntries\">\r\n");
      out.write("	            	<div class=\"availabilityEntry\">\r\n");
      out.write("	                	<table>\r\n");
      out.write("		                    <tr>\r\n");
      out.write("		                        <td>Hospital Name:</td>\r\n");
      out.write("		                        <td>\r\n");
      out.write("								    <input list=\"hospitals\" name=\"hospital_name\" style=\"width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;\">\r\n");
      out.write("								    <datalist id=\"hospitals\">\r\n");
      out.write("								        <option value=\"Asiri\">\r\n");
      out.write("						                <option value=\"Nawaloka\">\r\n");
      out.write("						                <option value=\"Lanka Hospitals\">\r\n");
      out.write("						                <option value=\"Hemas\">\r\n");
      out.write("						                <option value=\"Durdans\">\r\n");
      out.write("						                <option value=\"Seth Sevana Hospitals\">\r\n");
      out.write("						                <option value=\"Cooperative Hospital\">\r\n");
      out.write("						                <option value=\"Navinne\">\r\n");
      out.write("						                <option value=\"Ninewells\">\r\n");
      out.write("						                <option value=\"Kings Hospital\">\r\n");
      out.write("								    </datalist>\r\n");
      out.write("								</td>\r\n");
      out.write("		                    </tr>\r\n");
      out.write("		                    <tr>\r\n");
      out.write("		                        <td>Location:</td>\r\n");
      out.write("		                        <td><input type=\"text\" name=\"location\"></td>\r\n");
      out.write("		                    </tr>\r\n");
      out.write("	                    	<tr>\r\n");
      out.write("		                        <td>Day:</td>\r\n");
      out.write("		                        <td>\r\n");
      out.write("			                        <select name=\"day\" required style=\"width: 100%;\">\r\n");
      out.write("				                        <option value=\"Mon\">Monday</option>\r\n");
      out.write("				                        <option value=\"Tue\">Tuesday</option>\r\n");
      out.write("				                        <option value=\"Wed\">Wednesday</option>\r\n");
      out.write("				                        <option value=\"Thu\">Thursday</option>\r\n");
      out.write("				                        <option value=\"Fri\">Friday</option>\r\n");
      out.write("				                        <option value=\"Sat\">Saturday</option>\r\n");
      out.write("				                        <option value=\"Sun\">Sunday</option>\r\n");
      out.write("			                    	</select>\r\n");
      out.write("			                    </td>\r\n");
      out.write("	                    	</tr>\r\n");
      out.write("		                    <tr>\r\n");
      out.write("		                        <td>Time:</td>\r\n");
      out.write("		                        <td><input type=\"datetime-local\" name=\"time\" step=\"1\"></td>\r\n");
      out.write("		                    </tr>\r\n");
      out.write("		                    <tr>\r\n");
      out.write("		                        <td>Max Patients:</td>\r\n");
      out.write("		                        <td><input type=\"number\" name=\"max_patients\"></td>\r\n");
      out.write("		                    </tr>\r\n");
      out.write("		                    <tr>\r\n");
      out.write("		                        <td>Fee (Rs):</td>\r\n");
      out.write("		                        <td><input type=\"number\" step=\"0.01\" name=\"fee\"></td>\r\n");
      out.write("		                    </tr>\r\n");
      out.write("	                	</table>\r\n");
      out.write("	            	</div>\r\n");
      out.write("	        	</div>\r\n");
      out.write("	        	<button type=\"button\" onclick=\"addAvailability()\">Add Another Availability</button>\r\n");
      out.write("	    	</div>\r\n");
      out.write("	    	<br>\r\n");
      out.write("	    	<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		// This function adds another availability section when called\r\n");
      out.write("		function addAvailability() {\r\n");
      out.write("		    const container = document.getElementById('availabilityEntries');\r\n");
      out.write("		    const newEntry = document.createElement('div');\r\n");
      out.write("		    \r\n");
      out.write("		    newEntry.className = 'availabilityEntry';\r\n");
      out.write("		    newEntry.innerHTML = `\r\n");
      out.write("		    \r\n");
      out.write("		        <table>\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>Hospital Name:</td>\r\n");
      out.write("		                <td>\r\n");
      out.write("		                	<input list=\"hospitals\" name=\"hospital_name\" style=\"width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;\">\r\n");
      out.write("						    <datalist id=\"hospitals\">\r\n");
      out.write("						        <option value=\"Asiri\">\r\n");
      out.write("				                <option value=\"Nawaloka\">\r\n");
      out.write("				                <option value=\"Lanka Hospitals\">\r\n");
      out.write("				                <option value=\"Hemas\">\r\n");
      out.write("				                <option value=\"Durdans\">\r\n");
      out.write("				                <option value=\"Seth Sevana Hospitals\">\r\n");
      out.write("				                <option value=\"Cooperative Hospital\">\r\n");
      out.write("				                <option value=\"Navinne\">\r\n");
      out.write("				                <option value=\"Ninewells\">\r\n");
      out.write("				                <option value=\"Kings Hospital\">\r\n");
      out.write("				    		</datalist>\r\n");
      out.write("				    	</td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>Location:</td>\r\n");
      out.write("		                <td><input type=\"text\" name=\"location\"></td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>Day:</td>\r\n");
      out.write("		                <td>\r\n");
      out.write("			                <select name=\"day\" style=\"width: 100%;\" required>\r\n");
      out.write("				                <option value=\"Mon\">Monday</option>\r\n");
      out.write("				                <option value=\"Tue\">Tuesday</option>\r\n");
      out.write("				                <option value=\"Wed\">Wednesday</option>\r\n");
      out.write("				                <option value=\"Thu\">Thursday</option>\r\n");
      out.write("				                <option value=\"Fri\">Friday</option>\r\n");
      out.write("				                <option value=\"Sat\">Saturday</option>\r\n");
      out.write("				                <option value=\"Sun\">Sunday</option>\r\n");
      out.write("			        		</select>\r\n");
      out.write("		                </td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>Time:</td>\r\n");
      out.write("		                <td><input type=\"datetime-local\" name=\"time\" step=\"1\"></td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>Max Patients:</td>\r\n");
      out.write("		                <td><input type=\"number\" name=\"max_patients\"></td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		            <tr>\r\n");
      out.write("		                <td>Fee (Rs):</td>\r\n");
      out.write("		                <td><input type=\"number\" step=\"0.01\" name=\"fee\"></td>\r\n");
      out.write("		            </tr>\r\n");
      out.write("		        </table>\r\n");
      out.write("		    `;\r\n");
      out.write("		    container.appendChild(newEntry);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
