/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-15 03:09:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Admin Dashboard</title>\r\n");
      out.write("	<link rel=\"shortcut icon\" href=\"images/halomed1.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/dashboard.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"src/images/logo7.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" \r\n");
      out.write("          href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\" \r\n");
      out.write("          integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\" \r\n");
      out.write("          crossorigin=\"anonymous\" \r\n");
      out.write("          referrerpolicy=\"no-referrer\" />\r\n");
      out.write("         \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("            <div class=\"logo\"></div>\r\n");
      out.write("            \r\n");
      out.write("            <img src=\"images/halomed2.png\" alt = \"trendify\" width = \"180px\" height=\"180px\">\r\n");
      out.write("            \r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                \r\n");
      out.write("                    <li class=\"active\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <i class=\"fa fa-tachometer\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            <h4><span>Dashboard</span></h4>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"admin1.php\">\r\n");
      out.write("                            <i class=\"fa fa-users\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            <h4><span>Patient Management</span></h4>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"GetDoctorServlet\">\r\n");
      out.write("                            <i class=\"fa fa-user-md\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            <h4><span>Doctor Management</span></h4>\r\n");
      out.write("                            \r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"admin3.php\">\r\n");
      out.write("                            <i class=\"fa fa-check-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            <h4><span>Appointment Management</span></h4>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"logout\">\r\n");
      out.write("                        <a href=\"logout.php\">\r\n");
      out.write("                            <i class=\"fa fa-sign-out\" aria-hidden=\"true\"></i>\r\n");
      out.write("                            <h4><span>Log out</span></h4>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("        	</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("        \r\n");
      out.write("    		<div class=\"header\">\r\n");
      out.write("    		\r\n");
      out.write("       			<div class=\"title\">\r\n");
      out.write("	            	<span>Primary</span>\r\n");
      out.write("	            	<h2>Dashboard</h2>\r\n");
      out.write("        		</div>\r\n");
      out.write("        		\r\n");
      out.write("    		</div>\r\n");
      out.write("\r\n");
      out.write("    		<!-- Combined Overview (Sales, Orders, Customers, Inventory) -->\r\n");
      out.write("    		<div class=\"dashboard-section overview\">\r\n");
      out.write("    		\r\n");
      out.write("        		<div class=\"card sales\">\r\n");
      out.write("		            <h3>Total Registered Users</h3>\r\n");
      out.write("		            <p>15,245</p>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        \r\n");
      out.write("		        <div class=\"card orders\">\r\n");
      out.write("		            <h3>Total Active Doctors</h3>\r\n");
      out.write("		            <p>234</p>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        \r\n");
      out.write("		        <div class=\"card customers\">\r\n");
      out.write("		            <h3>Total Hospitals/Clinics</h3>\r\n");
      out.write("		            <p>55</p>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        \r\n");
      out.write("		        <div class=\"card inventory-item\">\r\n");
      out.write("		            <h3>Total appointments</h3>\r\n");
      out.write("		            <p>20,980</p>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        \r\n");
      out.write("		        <div class=\"card low-stock\">\r\n");
      out.write("		            <h3>Total revenue</h3>\r\n");
      out.write("		            <p>Rs.1500790.00</p>\r\n");
      out.write("		        </div>\r\n");
      out.write("		        \r\n");
      out.write("    		</div>\r\n");
      out.write("\r\n");
      out.write("		    <!-- Top Selling Products -->\r\n");
      out.write("		    <div class=\"dashboard-section\">\r\n");
      out.write("		        <h3>Today's Statistics</h3><br>\r\n");
      out.write("		        <ul class=\"top-products\">\r\n");
      out.write("		            <li>New Users - 120 sign-ups</li>\r\n");
      out.write("		            <li>Confirmed Appointments - 98 appointments</li>\r\n");
      out.write("		            <li>Busiest Hospital/s - Durdans Hospital, Colombo</li>\r\n");
      out.write("		        </ul>\r\n");
      out.write("		    </div>\r\n");
      out.write("		    \r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
