/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-10 06:40:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DoctorProfiles_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1749535243280L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1746951514155L));
    _jspx_dependants.put("jar:file:/D:/Eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Echanneling/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1749535243299L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- This shows added doctor and availability details as seen in the echannelling website-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>HaloMed | Our Doctors</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/halomed2.png\">\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/DoctorProfiles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

    String userType = (String) session.getAttribute("userType");
    Object sessionUser = session.getAttribute("user");
    String profileLink = "login.jsp";

    if (sessionUser != null && userType != null) {
        if ("patient".equals(userType)) {
            profileLink = "profile.jsp";
        } else if ("admin".equals(userType)) {
            profileLink = "adminDashboard.jsp";
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Header</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* Header Container */\r\n");
      out.write(".header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 90px;\r\n");
      out.write("    background: linear-gradient(90deg, #FFDEE9, #B5FFFC);\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    padding: 0 40px;\r\n");
      out.write("    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    position: relative;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    transition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header:hover {\r\n");
      out.write("    background: linear-gradient(90deg, #B5FFFC, #FFDEE9);\r\n");
      out.write("    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Logo Section */\r\n");
      out.write(".logo_box img {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    max-width: 200px;\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo_box img:hover {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navigation Section */\r\n");
      out.write(".nav_bar {\r\n");
      out.write("    flex-grow: 1;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    padding: 10px 18px;\r\n");
      out.write("    transition: background-color 0.3s, transform 0.3s;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a:hover {\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Profile Icon */\r\n");
      out.write(".user-cart {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons a img {\r\n");
      out.write("    width: 55px;\r\n");
      out.write("    height: 55px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    transition: box-shadow 0.3s ease, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons a:hover img {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("    box-shadow: 0 0 10px rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animated Underline Effect */\r\n");
      out.write(".nav_links a::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background: #333;\r\n");
      out.write("    transition: width 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a:hover::after {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo_box\">\r\n");
      out.write("        <img src=\"images/logo3.png\" alt=\"Logo\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav_bar\">\r\n");
      out.write("        <div class=\"nav_links\">\r\n");
      out.write("            <a href=\"index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"GetDoctorServlet?view=profiles\">Doctors</a>\r\n");
      out.write("            <a href=\"Search.jsp\">Appointment</a>\r\n");
      out.write("            <a href=\"lab_test.jsp\">Lab Test</a>\r\n");
      out.write("            <a href=\"contactSupport.jsp\">Contact Us</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"user-cart\">\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <a href=\"");
      out.print( profileLink );
      out.write("\">\r\n");
      out.write("                <img src=\"images/user-r.png\" alt=\"Profile\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div class=\"container my-5\">\r\n");
      out.write("    \r\n");
      out.write("    <h1 class=\"text-center mb-4\">Our Doctors</h1>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Search Form -->\r\n");
      out.write("    <form method=\"get\" action=\"GetDoctorServlet\" class=\"p-4 rounded\" style=\"background-color: #005aa7;\">\r\n");
      out.write("        <input type=\"hidden\" name=\"view\" value=\"profiles\" />\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row g-3 align-items-end\">\r\n");
      out.write("            \r\n");
      out.write("            <!-- Doctor Name -->\r\n");
      out.write("            <div class=\"col-md-2\">\r\n");
      out.write("                <label class=\"form-label text-white\">Doctor Name</label>\r\n");
      out.write("                <input type=\"text\" name=\"name\" class=\"form-control rounded\" placeholder=\"Search Doctor Name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <!-- Specialization Filter with Datalist -->\r\n");
      out.write("            <div class=\"col-md-2\">\r\n");
      out.write("                <label class=\"form-label text-white\">Specialization</label>\r\n");
      out.write("                <input list=\"specializations\" name=\"specialization\" class=\"form-control rounded\" placeholder=\"Choose or type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.specialization}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                <datalist id=\"specializations\">\r\n");
      out.write("                    <option value=\"Physician\">\r\n");
      out.write("                    <option value=\"Surgeon\">\r\n");
      out.write("                    <option value=\"Psychologist\">\r\n");
      out.write("                    <option value=\"Cardiologist\">\r\n");
      out.write("                    <option value=\"Dermatologist\">\r\n");
      out.write("                    <option value=\"Neurologist\">\r\n");
      out.write("                    <option value=\"Pediatrician\">\r\n");
      out.write("                    <option value=\"Hematologist\">\r\n");
      out.write("                    <option value=\"Gastroenterologist\">          \r\n");
      out.write("                </datalist>\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <!-- Hospital Filter with Datalist -->\r\n");
      out.write("            <div class=\"col-md-2\">\r\n");
      out.write("                <label class=\"form-label text-white\">Hospital</label>\r\n");
      out.write("                <input list=\"hospitals\" name=\"hospital\" class=\"form-control rounded\" placeholder=\"Choose or type\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.hospital}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                <datalist id=\"hospitals\">\r\n");
      out.write("                    <option value=\"Asiri\">\r\n");
      out.write("                    <option value=\"Nawaloka\">\r\n");
      out.write("                    <option value=\"Lanka Hospitals\">\r\n");
      out.write("                    <option value=\"Hemas\">\r\n");
      out.write("                    <option value=\"Durdans\">\r\n");
      out.write("                    <option value=\"Seth Sevana Hospitals\">\r\n");
      out.write("                    <option value=\"Cooperative Hospital\">\r\n");
      out.write("                    <option value=\"Navinne\">\r\n");
      out.write("                    <option value=\"Ninewells\">\r\n");
      out.write("                    <option value=\"Kings Hospital\">\r\n");
      out.write("                </datalist>\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <!-- Appointment Date Filter -->\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <label class=\"form-label text-white\">Date</label>\r\n");
      out.write("                <input type=\"date\" name=\"date\" class=\"form-control rounded\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("            </div>\r\n");
      out.write("    \r\n");
      out.write("            <!-- Search Button -->\r\n");
      out.write("            <div class=\"col-md-3\">\r\n");
      out.write("                <label class=\"form-label text-white d-block invisible\">Search</label>\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-light w-100 rounded\">Search</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <br><br>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Show message if no doctors available -->\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <div class=\"row g-3\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Loop through all doctors and display each in a card -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("footer {\r\n");
      out.write("	background: #0096c7;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 30px 0;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column h3 {\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-bottom: 2px solid #32CD32;\r\n");
      out.write("	padding-bottom: 5px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	transform: translateY(30px);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	transition: transform 0.6s ease-out, opacity 0.6s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column h3.show {\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li a:hover {\r\n");
      out.write("	color: #32CD32;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons a:hover {\r\n");
      out.write("	color: #32CD32;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer-container\">\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Services</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li><a href=\"GetDoctorServlet?view=profiles\">Our Doctors</a></li>\r\n");
      out.write("				<li><a href=\"lab_test.jsp\">Lab Tests</a></li>\r\n");
      out.write("				<li><a href=\"Search.jsp\">Doctor Appointments</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Quick Links</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"about_us.jsp\">About Us</a></li>\r\n");
      out.write("				<li><a href=\"contactSupport.jsp\">Contact Us</a></li>\r\n");
      out.write("				<li><a href=\"feedback.jsp\">Feedback</a></li>\r\n");
      out.write("				<li><a href=\"health_tips.jsp\">Health Tips</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Online Information</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"TermsandConditions.jsp\">Terms and Conditions</a></li>\r\n");
      out.write("				<li><a href=\"privacy_policy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("				<li><a href=\"refunds.jsp\">Refunds</a></li>\r\n");
      out.write("				<li><a href=\"faq.jsp\">FAQ</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Find Us On</h3>\r\n");
      out.write("			<div class=\"social-icons\">\r\n");
      out.write("				<a href=\"https://www.facebook.com\"><img src=\"images/facebook_logo.webp\" alt=\"Facebook\" width=\"47px\"></a>\r\n");
      out.write("				<a href=\"https://www.whatsapp.com\"><img src=\"images/whatsapp-r.png\" alt=\"WhatsApp\" width=\"52px\"></a>\r\n");
      out.write("				<a href=\"https://www.twitter.com\"><img src=\"images/twitter_l.webp\" alt=\"Twitter\" width=\"52px\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<p>&copy; 2025 E-Channeling. All rights reserved.</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("    document.querySelectorAll('.footer-column h3').forEach(h => {\r\n");
      out.write("      h.classList.add('show');\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS (optional, for any interactive components) -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /DoctorProfiles.jsp(86,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty alldctrs}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        <p class=\"text-center\">No doctors available at this time.</p>\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /DoctorProfiles.jsp(92,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("dctr");
    // /DoctorProfiles.jsp(92,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/DoctorProfiles.jsp(92,8) '${alldctrs}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${alldctrs}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <div class=\"col-lg-3 col-md-5 col-sm-12\">\r\n");
          out.write("                <div class=\"card doctor-card\">\r\n");
          out.write("                    <div class=\"card-body\">\r\n");
          out.write("                       <!-- Doctor Image and Basic Info -->\r\n");
          out.write("						");
          if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                        <h5 class=\"card-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctr.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctr.full_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h5>\r\n");
          out.write("                        <p class=\"card-text text-muted\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctr.specialization}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                        <!-- Availability Button -->\r\n");
          out.write("                        <a href=\"viewAvailability.jsp?doctorId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctr.doctor_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"availability-btn text-decoration-none d-inline-block text-center w-100\">\r\n");
          out.write("                            View Availability\r\n");
          out.write("                        </a>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </div>\r\n");
          out.write("            </div>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("						    ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("						    ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\r\n");
        out.write("						");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /DoctorProfiles.jsp(98,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty dctr.profile_photo}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("						        <img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctr.profile_photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" \r\n");
        out.write("						             alt=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dctr.full_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" \r\n");
        out.write("						             class=\"doctor-img\"\r\n");
        out.write("						             onerror=\"this.src='images/doctor25.jpg';\">\r\n");
        out.write("						    ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("						        <div class=\"doctor-img bg-secondary d-flex align-items-center justify-content-center\">\r\n");
        out.write("						            <img src=\"images/doctor25.jpg\" \r\n");
        out.write("						                 alt=\"Default Doctor Image\" \r\n");
        out.write("						                 class=\"doctor-img\">\r\n");
        out.write("						        </div>\r\n");
        out.write("						    ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
