/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-10 06:40:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.echannelling.model.LabTestModel;
import com.echannelling.service.LabTestController;

public final class edit_005flab_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.echannelling.service.LabTestController");
    _jspx_imports_classes.add("com.echannelling.model.LabTestModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>HaloMed | Edit Lab Test</title>\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"images/halomed2.png\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    /* General Reset */\r\n");
      out.write("    * {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Body Styling */\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: 'Poppins', sans-serif;\r\n");
      out.write("      background: linear-gradient(135deg, #e3f2fd, #bbdefb);\r\n");
      out.write("      min-height: 100vh; /* Ensure body takes at least full viewport height */\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column; /* Stack children vertically */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Header Styling (Assuming header.jsp has a <header> tag) */\r\n");
      out.write("    header {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      background: #34495e; /* Example background color */\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 15px 20px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Footer Styling (Assuming footer.jsp has a <footer> tag) */\r\n");
      out.write("    footer {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      background: #34495e; /* Example background color */\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 15px 20px;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-top: auto; /* Pushes footer to the bottom */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Form Container */\r\n");
      out.write("    .form-container {\r\n");
      out.write("      background: #ffffff;\r\n");
      out.write("      padding: 35px 40px;\r\n");
      out.write("      border-radius: 12px;\r\n");
      out.write("      box-shadow: 0 4px 30px rgba(0, 0, 0, 0.15);\r\n");
      out.write("      max-width: 450px;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      margin: 20px auto; /* Center horizontally with vertical spacing */\r\n");
      out.write("      transition: box-shadow 0.3s ease, transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-container:hover {\r\n");
      out.write("      box-shadow: 0 6px 45px rgba(0, 0, 0, 0.2);\r\n");
      out.write("      transform: translateY(-5px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-container h1 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      font-size: 28px;\r\n");
      out.write("      color: #34495e;\r\n");
      out.write("      margin-bottom: 25px;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Form Group Styling */\r\n");
      out.write("    .form-group {\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group label {\r\n");
      out.write("      display: block;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      margin-bottom: 8px;\r\n");
      out.write("      color: #2c3e50;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input, .form-group textarea {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      border: 1px solid #ddd;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      transition: border-color 0.3s ease;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input:focus, .form-group textarea:focus {\r\n");
      out.write("      border-color: #4CAF50;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group textarea {\r\n");
      out.write("      resize: vertical;\r\n");
      out.write("      height: 120px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Submit Button */\r\n");
      out.write("    .submit-btn {\r\n");
      out.write("      background: #3498db;\r\n");
      out.write("      border: none;\r\n");
      out.write("      padding: 14px;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      color: white;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      transition: background 0.3s ease, transform 0.2s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .submit-btn:hover {\r\n");
      out.write("      background: #2980b9;\r\n");
      out.write("      transform: scale(1.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Error Styling */\r\n");
      out.write("    .error {\r\n");
      out.write("      color: #e74c3c;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-top: 15px;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Link Styling */\r\n");
      out.write("    a {\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      color: #4CAF50;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a:hover {\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Responsive Design */\r\n");
      out.write("    @media screen and (max-width: 600px) {\r\n");
      out.write("      .form-container {\r\n");
      out.write("        padding: 20px 25px;\r\n");
      out.write("        margin: 15px; /* Reduce margin on smaller screens */\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-container h1 {\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .submit-btn {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      header, footer {\r\n");
      out.write("        padding: 10px 15px;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  ");

    String testIdParam = request.getParameter("test_id");
    LabTestModel labTest = null;

    if (testIdParam == null || testIdParam.trim().isEmpty()) {
  
      out.write("\r\n");
      out.write("    <div class=\"form-container\">\r\n");
      out.write("      <h1 class=\"error\">Error: Test ID not provided!</h1>\r\n");
      out.write("      <p><a href=\"admin_dashboard.jsp\">Go back to Dashboard</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("  ");

    } else {
        try {
            int testId = Integer.parseInt(testIdParam);
            labTest = LabTestController.getLabTestById(testId);

            if (labTest == null) {
  
      out.write("\r\n");
      out.write("                <div class=\"form-container\">\r\n");
      out.write("                  <h1 class=\"error\">Error: Lab Test not found!</h1>\r\n");
      out.write("                  <p><a href=\"admin_dashboard.jsp\">Go back to Dashboard</a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("  ");

            } else {
  
      out.write("\r\n");
      out.write("                <div class=\"form-container\">\r\n");
      out.write("                  <h1>Edit Lab Test</h1>\r\n");
      out.write("                  <form action=\"LabTestUpdateServlet\" method=\"post\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"test_id\" value=\"");
      out.print( labTest.getTestId() );
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"testName\">Test Name</label>\r\n");
      out.write("                      <input type=\"text\" name=\"test_name\" value=\"");
      out.print( labTest.getTestName() );
      out.write("\" required />\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"description\">Description</label>\r\n");
      out.write("                      <textarea name=\"description\" rows=\"4\" required>");
      out.print( labTest.getDescription() );
      out.write("</textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      <label for=\"price\">Price (LKR)</label>\r\n");
      out.write("                      <input type=\"number\" name=\"price\" step=\"0.01\" value=\"");
      out.print( labTest.getPrice() );
      out.write("\" required />\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"submit-btn\">Update Test</button>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("  ");

            }
        } catch (NumberFormatException e) {
  
      out.write("\r\n");
      out.write("        <div class=\"form-container\">\r\n");
      out.write("          <h1 class=\"error\">Error: Invalid Test ID format.</h1>\r\n");
      out.write("          <p><a href=\"admin_dashboard.jsp\">Go back to Dashboard</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("  ");

        }
    }
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
