/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-10 06:20:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.echannelling.model.User;
import com.echannelling.service.UserDAO;

public final class editPatient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.echannelling.model.User");
    _jspx_imports_classes.add("com.echannelling.service.UserDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	//Retrieve patient ID from request parameter
    int id = Integer.parseInt(request.getParameter("id"));

	//Instantiate UserDAO to access patient data
    UserDAO dao = new UserDAO();
    User patient = dao.getUserById(id);  // Fetch patient details using ID

 	// Retrieve and clear any error message stored in the session
    String error = (String) session.getAttribute("error");
    session.removeAttribute("error"); // Clear it after retrieving
    String contextPath = request.getContextPath();  // Get context path for dynamic resource linking

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>HaloMed | Edit Patient</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.print( contextPath );
      out.write("/images/halomed2.png\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 60px 0;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: #d1eafd;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            background: #b5ddfc;\r\n");
      out.write("            backdrop-filter: blur(15px);\r\n");
      out.write("            padding: 50px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.25);\r\n");
      out.write("            animation: fadeIn 1s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from {opacity: 0; transform: translateY(20px);}\r\n");
      out.write("            to {opacity: 1; transform: translateY(0);}\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"],\r\n");
      out.write("        input[type=\"email\"],\r\n");
      out.write("        input[type=\"password\"],\r\n");
      out.write("        input[type=\"file\"],\r\n");
      out.write("        select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            border: 1px solid #ccc;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"submit\"] {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background-color: #007bff;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: background 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"submit\"]:hover {\r\n");
      out.write("            background-color: #0056b3;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link a {\r\n");
      out.write("            color: #004c99;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .message-error {\r\n");
      out.write("            background-color: #ffcccc;\r\n");
      out.write("            color: #a70000;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #imagePreview {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            display: ");
      out.print( patient.getProfileImage() != null && !patient.getProfileImage().isEmpty() ? "block" : "none" );
      out.write(";\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write(" 		// Function to validate form inputs before submission\r\n");
      out.write("        function validateForm() {\r\n");
      out.write("            const email = document.forms[\"editForm\"][\"email\"].value;\r\n");
      out.write("            const phone = document.forms[\"editForm\"][\"phone\"].value;\r\n");
      out.write("            const nic = document.forms[\"editForm\"][\"nic\"].value;\r\n");
      out.write("            const password = document.forms[\"editForm\"][\"password\"].value;\r\n");
      out.write("            const fileInput = document.forms[\"editForm\"][\"profileImage\"].files[0];\r\n");
      out.write("\r\n");
      out.write("            const emailPattern = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("            const phonePattern = /^0\\d{9}$/;\r\n");
      out.write("            const nicPattern = /^\\d{9}[vV]$|^\\d{12}$/;\r\n");
      out.write("            const passwordPattern = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*#?&]).{8,}$/;\r\n");
      out.write("            const allowedImageTypes = ['image/jpeg', 'image/png', 'image/gif'];\r\n");
      out.write("\r\n");
      out.write("            if (!emailPattern.test(email)) {\r\n");
      out.write("                alert(\"Invalid email format.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (!phonePattern.test(phone)) {\r\n");
      out.write("                alert(\"Phone must start with 0 and have 10 digits.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (!nicPattern.test(nic)) {\r\n");
      out.write("                alert(\"Invalid NIC format.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (!passwordPattern.test(password)) {\r\n");
      out.write("                alert(\"Password must be at least 8 characters long and contain uppercase, lowercase, digit, and special character.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if (fileInput && !allowedImageTypes.includes(fileInput.type)) {\r\n");
      out.write("                alert(\"Only JPG, PNG, or GIF images are allowed.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            return true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Image preview\r\n");
      out.write("        document.getElementById('profileImage').addEventListener('change', function(event) {\r\n");
      out.write("            const file = event.target.files[0];\r\n");
      out.write("            const preview = document.getElementById('imagePreview');\r\n");
      out.write("            const allowedTypes = ['image/jpeg', 'image/png', 'image/gif'];\r\n");
      out.write("\r\n");
      out.write("            if (file && allowedTypes.includes(file.type)) {\r\n");
      out.write("                const reader = new FileReader();\r\n");
      out.write("                reader.onload = function(e) {\r\n");
      out.write("                    preview.src = e.target.result;\r\n");
      out.write("                    preview.style.display = 'block';\r\n");
      out.write("                };\r\n");
      out.write("                reader.readAsDataURL(file);\r\n");
      out.write("            } else {\r\n");
      out.write("                preview.style.display = 'none';\r\n");
      out.write("                alert('Please select a valid image file (JPG, PNG, GIF).');\r\n");
      out.write("                event.target.value = ''; // Clear invalid file\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        ");
 if (error != null) { 
      out.write("\r\n");
      out.write("            <div class=\"message-error\">");
      out.print( error );
      out.write("</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h2><i class=\"fa-solid fa-user-plus\"></i> Edit Patient</h2>\r\n");
      out.write("\r\n");
      out.write("        <form name=\"editForm\" action=\"UpdatePatientServlet\" method=\"post\" enctype=\"multipart/form-data\" onsubmit=\"return validateForm()\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id\" value=\"");
      out.print( patient.getId() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("            <label>Title</label>\r\n");
      out.write("            <select name=\"title\" required>\r\n");
      out.write("                ");

                    String[] titles = {"Mr.", "Ms.", "Miss.", "Mrs.", "Dr.", "Prof.", "Rev.", "Sis.", "Hons.", "Baby.", "Master."};
                    for (String title : titles) {
                
      out.write("\r\n");
      out.write("                    <option value=\"");
      out.print( title );
      out.write('"');
      out.write(' ');
      out.print( title.equals(patient.getTitle()) ? "selected" : "" );
      out.write('>');
      out.print( title );
      out.write("</option>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <label>First Name</label>\r\n");
      out.write("            <input type=\"text\" name=\"firstName\" value=\"");
      out.print( patient.getFirstName() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>Last Name</label>\r\n");
      out.write("            <input type=\"text\" name=\"lastName\" value=\"");
      out.print( patient.getLastName() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>Email</label>\r\n");
      out.write("            <input type=\"email\" name=\"email\" value=\"");
      out.print( patient.getEmail() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>Phone</label>\r\n");
      out.write("            <input type=\"text\" name=\"phone\" value=\"");
      out.print( patient.getPhone() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>NIC</label>\r\n");
      out.write("            <input type=\"text\" name=\"nic\" value=\"");
      out.print( patient.getNic() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>Address</label>\r\n");
      out.write("            <input type=\"text\" name=\"address\" value=\"");
      out.print( patient.getAddress() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label>Password</label>\r\n");
      out.write("            <input type=\"password\" name=\"password\" value=\"");
      out.print( patient.getPassword() );
      out.write("\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"profileImage\">Profile Image</label>\r\n");
      out.write("            <img id=\"imagePreview\" src=\"");
      out.print( patient.getProfileImage() != null && !patient.getProfileImage().isEmpty() ? contextPath + "/" + patient.getProfileImage() : contextPath + "/images/profile1.jpg" );
      out.write("\" alt=\"Image Preview\">\r\n");
      out.write("            <input type=\"file\" name=\"profileImage\" id=\"profileImage\" accept=\"image/*\">\r\n");
      out.write("\r\n");
      out.write("            <input type=\"submit\" value=\"Update Patient\">\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"back-link\">\r\n");
      out.write("            <a href=\"patientManagement.jsp\">Back to Dashboard</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
