/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-10 06:33:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1749535243280L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1749535243299L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>HaloMed | Home</title>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/a076d05399.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/halomed2.png\">\r\n");
      out.write("	<Style>\r\n");
      out.write("		/* General Styles */\r\n");
      out.write("	body {\r\n");
      out.write("		font-family: Arial, sans-serif;\r\n");
      out.write("		margin: 0;\r\n");
      out.write("		padding: 0;\r\n");
      out.write("		background-color: white;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Slideshow Section */\r\n");
      out.write("	.slideshow-container {\r\n");
      out.write("		position: relative;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 600px; /* Adjust height as needed */\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.slides {\r\n");
      out.write("		display: none;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("		object-fit: cover; /* Ensures image covers container */\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Book Appointment Section */\r\n");
      out.write("	.hero {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		padding: 60px 20px;\r\n");
      out.write("		/*background: linear-gradient(to right, #0096c7, #00cec8); */\r\n");
      out.write("		color: white;\r\n");
      out.write("		background: #1e3a5f;\r\n");
      out.write("	}\r\n");
      out.write("	.hero p{\r\n");
      out.write("	     color: white;\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.hero button {\r\n");
      out.write("		background: #0096c7;\r\n");
      out.write("		border: none;\r\n");
      out.write("		padding: 15px 25px;\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		color: white;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		transition: background 0.3s;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.hero button:hover {\r\n");
      out.write("		background: #0077b6;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Quick Access Section */\r\n");
      out.write("	.quick-access {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		margin: 30px 0;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.card {\r\n");
      out.write("		background: white;\r\n");
      out.write("		padding: 20px;\r\n");
      out.write("		margin: 10px;\r\n");
      out.write("		width: 200px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.2);\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.card img {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.card:hover {\r\n");
      out.write("		background: #caf0f8;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.quality-data {\r\n");
      out.write("		text-align: left;\r\n");
      out.write("		padding: 60px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	h2 {\r\n");
      out.write("		color: #333;\r\n");
      out.write("		margin-bottom: 40px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.data-grid {\r\n");
      out.write("		display: grid;\r\n");
      out.write("		grid-template-columns: repeat(3, 1fr); /* Three items per row */\r\n");
      out.write("		gap: 15px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	.data-card {\r\n");
      out.write("		background-color: #1e3a5f;\r\n");
      out.write("		color: white;\r\n");
      out.write("		padding: 30px;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		min-width: 200px;\r\n");
      out.write("		flex: 1;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.percentage {\r\n");
      out.write("		font-size: 1.8em;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.description {\r\n");
      out.write("		font-size: 0.9em;\r\n");
      out.write("		margin-top: 5px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* ================== SECTION BREAK ================== */\r\n");
      out.write("\r\n");
      out.write("	/* Grid Section Background */\r\n");
      out.write("	.grid-section {\r\n");
      out.write("		background: url('images/back1.jpg') no-repeat center center/cover;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		padding: 50px 0;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Header Section */\r\n");
      out.write("	.grid-header {\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		margin-bottom: 30px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.grid-header h2 {\r\n");
      out.write("		font-size: 32px;\r\n");
      out.write("		color:#0096c7; \r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.grid-header p {\r\n");
      out.write("		font-size: 18px;\r\n");
      out.write("		color: gray;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Grid Cards Header Default Style */\r\n");
      out.write("	.card h3 {\r\n");
      out.write("		position: relative;\r\n");
      out.write("		transform: translateY(30px); /* Start slightly below */\r\n");
      out.write("		opacity: 0;\r\n");
      out.write("		transition: transform 0.6s ease-out, opacity 0.6s ease-out;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* When header is in view, move it up */\r\n");
      out.write("	.card h3.show {\r\n");
      out.write("		transform: translateY(0);\r\n");
      out.write("		opacity: 1;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Grid Layout */\r\n");
      out.write("	.container {\r\n");
      out.write("		display: grid;\r\n");
      out.write("		grid-template-columns: repeat(4, 1fr);\r\n");
      out.write("		gap: 30px;\r\n");
      out.write("		width: 80%;\r\n");
      out.write("		max-width: 1200px;\r\n");
      out.write("    	margin: 0 auto;\r\n");
      out.write("    	box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Clickable Cards */\r\n");
      out.write("	.container .card {\r\n");
      out.write("		background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("		padding: 30px;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		transition: transform 0.3s, background 0.3s;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("    	box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Card Hover Effect */\r\n");
      out.write("	.container .card:hover {\r\n");
      out.write("		transform: scale(1.05);\r\n");
      out.write("		background: #caf0f8;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* Responsive Design */\r\n");
      out.write("	@media (max-width: 1024px) {\r\n");
      out.write("		.container {\r\n");
      out.write("			grid-template-columns: repeat(2, 1fr);\r\n");
      out.write("			width: 90%;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	@media (max-width: 600px) {\r\n");
      out.write("		.container {\r\n");
      out.write("			grid-template-columns: repeat(1, 1fr);\r\n");
      out.write("			width: 90%;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	.additional-section {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		padding: 40px;\r\n");
      out.write("		background-color: white; /* Adjust as needed */\r\n");
      out.write("		margin-top: 40px;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.left-side {\r\n");
      out.write("		flex: 1;\r\n");
      out.write("		padding-right: 20px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	.right-side {\r\n");
      out.write("		flex: 1;\r\n");
      out.write("		padding-left: 20px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/*.right-side img {\r\n");
      out.write("		width: 100%; /* Ensure it fits within its container \r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		box-shadow: white;\r\n");
      out.write("	} */\r\n");
      out.write("\r\n");
      out.write("	.right-side img {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		box-shadow: white;\r\n");
      out.write("		transform: translateY(100px); /* Start below */\r\n");
      out.write("		opacity: 0; /* Initially invisible */\r\n");
      out.write("		transition: transform 1s ease-out, opacity 1s ease-out;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/* When scrolled into view, apply animation */\r\n");
      out.write("	.right-side img.show {\r\n");
      out.write("		transform: translateY(0);\r\n");
      out.write("		opacity: 1;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	h2 {\r\n");
      out.write("		color: #0077b6; /* Adjust the color */\r\n");
      out.write("		font-size: 24px;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		margin-bottom: 20px;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	p {\r\n");
      out.write("		color: #333;\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("		line-height: 1.6;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>	\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');

    String userType = (String) session.getAttribute("userType");
    Object sessionUser = session.getAttribute("user");
    String profileLink = "login.jsp";

    if (sessionUser != null && userType != null) {
        if ("patient".equals(userType)) {
            profileLink = "profile.jsp";
        } else if ("admin".equals(userType)) {
            profileLink = "adminDashboard.jsp";
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Header</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* Header Container */\r\n");
      out.write(".header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 90px;\r\n");
      out.write("    background: linear-gradient(90deg, #FFDEE9, #B5FFFC);\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    padding: 0 40px;\r\n");
      out.write("    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    position: relative;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    transition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header:hover {\r\n");
      out.write("    background: linear-gradient(90deg, #B5FFFC, #FFDEE9);\r\n");
      out.write("    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Logo Section */\r\n");
      out.write(".logo_box img {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    max-width: 200px;\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo_box img:hover {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navigation Section */\r\n");
      out.write(".nav_bar {\r\n");
      out.write("    flex-grow: 1;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    padding: 10px 18px;\r\n");
      out.write("    transition: background-color 0.3s, transform 0.3s;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a:hover {\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Profile Icon */\r\n");
      out.write(".user-cart {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons a img {\r\n");
      out.write("    width: 55px;\r\n");
      out.write("    height: 55px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    transition: box-shadow 0.3s ease, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons a:hover img {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("    box-shadow: 0 0 10px rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animated Underline Effect */\r\n");
      out.write(".nav_links a::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background: #333;\r\n");
      out.write("    transition: width 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a:hover::after {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo_box\">\r\n");
      out.write("        <img src=\"images/logo3.png\" alt=\"Logo\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav_bar\">\r\n");
      out.write("        <div class=\"nav_links\">\r\n");
      out.write("            <a href=\"index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"GetDoctorServlet?view=profiles\">Doctors</a>\r\n");
      out.write("            <a href=\"Search.jsp\">Appointment</a>\r\n");
      out.write("            <a href=\"lab_test.jsp\">Lab Test</a>\r\n");
      out.write("            <a href=\"contactSupport.jsp\">Contact Us</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"user-cart\">\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <a href=\"");
      out.print( profileLink );
      out.write("\">\r\n");
      out.write("                <img src=\"images/user-r.png\" alt=\"Profile\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   <!-- Slideshow -->\r\n");
      out.write("<div class=\"slideshow-container\">\r\n");
      out.write("    <img class=\"slides\" src=\"images/slide311.JPG\" alt=\"Slide 1\">\r\n");
      out.write("    <img class=\"slides\" src=\"images/slide2.JPG\" alt=\"Slide 2\">\r\n");
      out.write("    <img class=\"slides\" src=\"images/slide5.jpg\" alt=\"Slide 3\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Book Now Section -->\r\n");
      out.write("<section id=\"home\" class=\"hero\">\r\n");
      out.write("    <h1>Book Your Doctor's Appointment Online</h1>\r\n");
      out.write("    <p>Find experienced doctors and schedule your visit easily.</p>\r\n");
      out.write("    <button onclick=\"location.href='Search.jsp'\">Book Now</button>\r\n");
      out.write("\r\n");
      out.write("</section>  \r\n");
      out.write("\r\n");
      out.write("<div class=\"quality-data\">\r\n");
      out.write("    <h2>Quality Data</h2>\r\n");
      out.write("    <div class=\"data-grid\">\r\n");
      out.write("        <div class=\"data-card\">\r\n");
      out.write("            <span class=\"percentage\">94.82%</span>\r\n");
      out.write("            <span class=\"description\">Patient Satisfaction Rate on Services</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"data-card\">\r\n");
      out.write("            <span class=\"percentage\">97.30%</span>\r\n");
      out.write("            <span class=\"description\">Compliance to Correct Patient Identification</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"data-card\">\r\n");
      out.write("            <span class=\"percentage\">89.8%</span>\r\n");
      out.write("            <span class=\"description\">Quick Booking Process</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"data-card\">\r\n");
      out.write("            <span class=\"percentage\">85.8%</span>\r\n");
      out.write("            <span class=\"description\">Efficient Appointment Management</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"data-card\">\r\n");
      out.write("            <span class=\"percentage\">10.2%</span>\r\n");
      out.write("            <span class=\"description\">Late Booking Process</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"data-card\">\r\n");
      out.write("            <span class=\"percentage\">0.00%</span>\r\n");
      out.write("            <span class=\"description\">Incorrect Appointments</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ==================== Quick Access Grid Section ==================== -->\r\n");
      out.write("<section class=\"grid-section\">\r\n");
      out.write("    <!-- Header for the Grid Section -->\r\n");
      out.write("    <div class=\"grid-header\">\r\n");
      out.write("        <h2>Use the convenience of our online services here</h2>\r\n");
      out.write("        <p>Caring for the health of you and your family</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Grid Container -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("	\r\n");
      out.write("	    \r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='Search.jsp'\">\r\n");
      out.write("            <h3>CONSULTATION BOOKINGS</h3>\r\n");
      out.write("            <p>Make your consultant channeling appointment here.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("		\r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='lab_test.jsp'\">\r\n");
      out.write("            <h3>BOOKING LAB TESTS</h3>\r\n");
      out.write("            <p>Make your lab test appointment here.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='GetDoctorServlet?view=profiles'\">\r\n");
      out.write("            <h3>AVAILABILITY OF DOCTORS</h3>\r\n");
      out.write("            <p>Monitor the available doctors.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("		\r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='register.jsp'\">\r\n");
      out.write("            <h3>PRE-REGISTRATION</h3>\r\n");
      out.write("            <p>Complete your registration before your visit.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='online_pharmacy.jsp'\">\r\n");
      out.write("            <h3>ONLINE PHARMACY</h3>\r\n");
      out.write("            <p>Order prescriptions online for home delivery.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='about_us.jsp'\">\r\n");
      out.write("            <h3>ABOUT US</h3>\r\n");
      out.write("            <p>Know about us here and make sure.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='contactSupport.jsp'\">\r\n");
      out.write("            <h3>CONTACT US</h3>\r\n");
      out.write("            <p>Quickly contact us here.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card\" onclick=\"location.href='feedback.jsp'\">\r\n");
      out.write("            <h3>PATIENT FEEDBACK</h3>\r\n");
      out.write("            <p>Share your experience with us.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"additional-section\">\r\n");
      out.write("    <div class=\"left-side\">\r\n");
      out.write("        <h2>WHY PATIENTS CHOOSE US</h2>\r\n");
      out.write("        <p>At HaloMed, we prioritize convenience, reliability, and accessibility to provide you with a seamless e-channeling experience. Our platform connects you with top healthcare professionals across various specialties, allowing you to book appointments from the comfort of your home. With user-friendly navigation, real-time availability updates, and secure payment options, we ensure that your healthcare needs are met with the utmost care and efficiency. Choose us for a hassle-free, efficient, and reliable way to manage your health appointments anytime, anywhere.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"right-side\">\r\n");
      out.write("        <img src=\"images/back2.jpg\" alt=\"Description of image\">\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("     \r\n");
      out.write("    <script>\r\n");
      out.write("		// Function to handle booking button click\r\n");
      out.write("		function bookNow() {\r\n");
      out.write("			alert(\"Redirecting to booking page...\");\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Wait for the DOM to fully load before running the script\r\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("			// Animating the hero section\r\n");
      out.write("			const heroSection = document.querySelector(\".hero\");\r\n");
      out.write("			heroSection.style.opacity = 0;\r\n");
      out.write("			heroSection.style.transform = \"translateY(-20px)\";\r\n");
      out.write("			\r\n");
      out.write("			setTimeout(() => {\r\n");
      out.write("				heroSection.style.transition = \"all 1s ease-out\";\r\n");
      out.write("				heroSection.style.opacity = 1;\r\n");
      out.write("				heroSection.style.transform = \"translateY(0)\";\r\n");
      out.write("			}, 300);\r\n");
      out.write("\r\n");
      out.write("			// Hover effects for navigation links\r\n");
      out.write("			const navLinks = document.querySelectorAll(\"nav ul li a\");\r\n");
      out.write("			navLinks.forEach(link => {\r\n");
      out.write("				link.addEventListener(\"mouseover\", function () {\r\n");
      out.write("					this.style.transform = \"scale(1.1)\";\r\n");
      out.write("				});\r\n");
      out.write("				link.addEventListener(\"mouseleave\", function () {\r\n");
      out.write("					this.style.transform = \"scale(1)\";\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//slide bar\r\n");
      out.write("		   let slideIndex = 0;\r\n");
      out.write("		function showSlides() {\r\n");
      out.write("			let slides = document.getElementsByClassName(\"slides\");\r\n");
      out.write("			for (let i = 0; i < slides.length; i++) {\r\n");
      out.write("				slides[i].style.display = \"none\";\r\n");
      out.write("			}\r\n");
      out.write("			slideIndex++;\r\n");
      out.write("			if (slideIndex > slides.length) { slideIndex = 1; }\r\n");
      out.write("			slides[slideIndex - 1].style.display = \"block\";\r\n");
      out.write("			setTimeout(showSlides, 3000); // Change image every 3 seconds\r\n");
      out.write("		}\r\n");
      out.write("		showSlides();\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("			const gridCardHeaders = document.querySelectorAll(\".card h3\");\r\n");
      out.write("\r\n");
      out.write("			const observer = new IntersectionObserver((entries) => {\r\n");
      out.write("				entries.forEach(entry => {\r\n");
      out.write("					if (entry.isIntersecting) {\r\n");
      out.write("						entry.target.classList.add(\"show\");\r\n");
      out.write("					} else {\r\n");
      out.write("						entry.target.classList.remove(\"show\");\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}, { threshold: 0.5 }); // Trigger when 50% of the element is in view\r\n");
      out.write("\r\n");
      out.write("			gridCardHeaders.forEach(header => {\r\n");
      out.write("				observer.observe(header);\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		//footer header animation\r\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("			const footerHeaders = document.querySelectorAll(\".footer-column h3\");\r\n");
      out.write("\r\n");
      out.write("			const observer = new IntersectionObserver((entries) => {\r\n");
      out.write("				entries.forEach(entry => {\r\n");
      out.write("					if (entry.isIntersecting) {\r\n");
      out.write("						entry.target.classList.add(\"show\");\r\n");
      out.write("					} else {\r\n");
      out.write("						entry.target.classList.remove(\"show\");\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			}, { threshold: 0.5 }); // Trigger when 50% of the element is in view\r\n");
      out.write("\r\n");
      out.write("			footerHeaders.forEach(header => {\r\n");
      out.write("				observer.observe(header);\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		//image animation\r\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("			const rightImage = document.querySelector(\".right-side img\");\r\n");
      out.write("\r\n");
      out.write("			function checkScroll() {\r\n");
      out.write("				if (!rightImage) return; // Ensure element exists\r\n");
      out.write("				\r\n");
      out.write("				const sectionPosition = rightImage.getBoundingClientRect().top;\r\n");
      out.write("				const screenHeight = window.innerHeight;\r\n");
      out.write("\r\n");
      out.write("				if (sectionPosition < screenHeight - 100) { \r\n");
      out.write("					rightImage.classList.add(\"show\"); // Add class when in view\r\n");
      out.write("					window.removeEventListener(\"scroll\", checkScroll); // Run only once\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			window.addEventListener(\"scroll\", checkScroll);\r\n");
      out.write("			checkScroll(); // Run once to check if it's already visible on load\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		function toggleMenu() {\r\n");
      out.write("			document.querySelector('.nav-links').classList.toggle('active');\r\n");
      out.write("		} \r\n");
      out.write("	</script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("footer {\r\n");
      out.write("	background: #0096c7;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 30px 0;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column h3 {\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-bottom: 2px solid #32CD32;\r\n");
      out.write("	padding-bottom: 5px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	transform: translateY(30px);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	transition: transform 0.6s ease-out, opacity 0.6s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column h3.show {\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li a:hover {\r\n");
      out.write("	color: #32CD32;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons a:hover {\r\n");
      out.write("	color: #32CD32;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer-container\">\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Services</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li><a href=\"GetDoctorServlet?view=profiles\">Our Doctors</a></li>\r\n");
      out.write("				<li><a href=\"lab_test.jsp\">Lab Tests</a></li>\r\n");
      out.write("				<li><a href=\"Search.jsp\">Doctor Appointments</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Quick Links</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"about_us.jsp\">About Us</a></li>\r\n");
      out.write("				<li><a href=\"contactSupport.jsp\">Contact Us</a></li>\r\n");
      out.write("				<li><a href=\"feedback.jsp\">Feedback</a></li>\r\n");
      out.write("				<li><a href=\"health_tips.jsp\">Health Tips</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Online Information</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"TermsandConditions.jsp\">Terms and Conditions</a></li>\r\n");
      out.write("				<li><a href=\"privacy_policy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("				<li><a href=\"refunds.jsp\">Refunds</a></li>\r\n");
      out.write("				<li><a href=\"faq.jsp\">FAQ</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Find Us On</h3>\r\n");
      out.write("			<div class=\"social-icons\">\r\n");
      out.write("				<a href=\"https://www.facebook.com\"><img src=\"images/facebook_logo.webp\" alt=\"Facebook\" width=\"47px\"></a>\r\n");
      out.write("				<a href=\"https://www.whatsapp.com\"><img src=\"images/whatsapp-r.png\" alt=\"WhatsApp\" width=\"52px\"></a>\r\n");
      out.write("				<a href=\"https://www.twitter.com\"><img src=\"images/twitter_l.webp\" alt=\"Twitter\" width=\"52px\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<p>&copy; 2025 E-Channeling. All rights reserved.</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("    document.querySelectorAll('.footer-column h3').forEach(h => {\r\n");
      out.write("      h.classList.add('show');\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
