/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-19 06:50:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class refunds_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1747636152150L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1747636152150L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>HeloMed - Refund Policy</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f5f5f5; /* Light gray background */\r\n");
      out.write("            color: #757575; /* Soft gray for text */\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 800px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-title {\r\n");
      out.write("            background-color: #1976d2; /* Primary blue */\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-radius: 8px 8px 0 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .page-title h1 {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .content {\r\n");
      out.write("            background-color: white; /* White content background */\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 0 0 8px 8px;\r\n");
      out.write("            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: #43a047; /* Green for headings */\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        p {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul, ol {\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            padding-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        li {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            color: #1976d2; /* Blue for links */\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .contact-info {\r\n");
      out.write("            background-color: #f5f5f5; /* Light gray for contact section */\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .contact-info p {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 600px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .content {\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .page-title h1 {\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            h2 {\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

    String userType = (String) session.getAttribute("userType");
    Object sessionUser = session.getAttribute("user");
    String profileLink = "login.jsp";

    if (sessionUser != null && userType != null) {
        if ("patient".equals(userType)) {
            profileLink = "profile.jsp";
        } else if ("admin".equals(userType)) {
            profileLink = "adminDashboard.jsp";
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Header</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* Header Container */\r\n");
      out.write(".header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 90px;\r\n");
      out.write("    background: linear-gradient(90deg, #FFDEE9, #B5FFFC);\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    padding: 0 40px;\r\n");
      out.write("    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    position: relative;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    transition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header:hover {\r\n");
      out.write("    background: linear-gradient(90deg, #B5FFFC, #FFDEE9);\r\n");
      out.write("    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Logo Section */\r\n");
      out.write(".logo_box img {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    max-width: 200px;\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo_box img:hover {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navigation Section */\r\n");
      out.write(".nav_bar {\r\n");
      out.write("    flex-grow: 1;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    padding: 10px 18px;\r\n");
      out.write("    transition: background-color 0.3s, transform 0.3s;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a:hover {\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Profile Icon */\r\n");
      out.write(".user-cart {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons a img {\r\n");
      out.write("    width: 55px;\r\n");
      out.write("    height: 55px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    transition: box-shadow 0.3s ease, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons a:hover img {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("    box-shadow: 0 0 10px rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animated Underline Effect */\r\n");
      out.write(".nav_links a::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background: #333;\r\n");
      out.write("    transition: width 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a:hover::after {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo_box\">\r\n");
      out.write("        <img src=\"images/logo3.png\" alt=\"Logo\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav_bar\">\r\n");
      out.write("        <div class=\"nav_links\">\r\n");
      out.write("            <a href=\"index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"GetDoctorServlet?view=profiles\">Doctors</a>\r\n");
      out.write("            <a href=\"Search.jsp\">Appointment</a>\r\n");
      out.write("            <a href=\"lab_test.jsp\">Lab Test</a>\r\n");
      out.write("            <a href=\"contactSupport.jsp\">Contact Us</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"user-cart\">\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <a href=\"");
      out.print( profileLink );
      out.write("\">\r\n");
      out.write("                <img src=\"images/user-r.png\" alt=\"Profile\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"page-title\">\r\n");
      out.write("            <h1>HeloMed Refund Policy</h1>\r\n");
      out.write("            <p>Your trusted e-channeling service</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h2>Our Commitment</h2>\r\n");
      out.write("            <p>At HeloMed, we strive to provide exceptional medical consultation services through our e-channeling platform. We understand that circumstances may arise where you need to request a refund. This policy outlines the conditions under which refunds may be processed.</p>\r\n");
      out.write("\r\n");
      out.write("            <h2>Refund Eligibility</h2>\r\n");
      out.write("            <p>Refunds may be considered under the following circumstances:</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><strong>Cancellation by HeloMed:</strong> If we cancel an appointment due to unforeseen circumstances, you are eligible for a full refund.</li>\r\n");
      out.write("                <li><strong>Technical Issues:</strong> If you experience technical difficulties caused by our platform that prevent you from attending a scheduled consultation, you may request a refund.</li>\r\n");
      out.write("                <li><strong>Doctor No-Show:</strong> If a doctor fails to attend a scheduled consultation, you are eligible for a full refund.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <h2>Non-Refundable Cases</h2>\r\n");
      out.write("            <p>Refunds will not be provided in the following cases:</p>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><strong>Patient Cancellation:</strong> Cancellations made less than 24 hours before the appointment are not eligible for a refund.</li>\r\n");
      out.write("                <li><strong>No-Show:</strong> If you fail to attend a scheduled consultation without prior notice, no refund will be issued.</li>\r\n");
      out.write("                <li><strong>Service Satisfaction:</strong> Refunds are not provided based on dissatisfaction with the consultation content, as this is subjective.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <h2>Refund Process</h2>\r\n");
      out.write("            <p>To request a refund, please follow these steps:</p>\r\n");
      out.write("            <ol>\r\n");
      out.write("                <li>Contact our support team within 7 days of the appointment via email or our support portal.</li>\r\n");
      out.write("                <li>Provide your appointment details, including the appointment ID and reason for the refund request.</li>\r\n");
      out.write("                <li>Our team will review your request and respond within 3-5 business days.</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("            <p>Approved refunds will be processed to the original payment method within 7-10 business days.</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"contact-info\">\r\n");
      out.write("                <h2>Contact Us</h2>\r\n");
      out.write("                <p>Email: support@helomed.com</p>\r\n");
      out.write("                <p>Phone: +94 11 472 1678</p>\r\n");
      out.write("                <p>Support Portal: <a href=\"https://www.helomed.com/support\">www.helomed.com/support</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("footer {\r\n");
      out.write("	background: #0096c7;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 30px 0;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column h3 {\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-bottom: 2px solid #32CD32;\r\n");
      out.write("	padding-bottom: 5px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	transform: translateY(30px);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	transition: transform 0.6s ease-out, opacity 0.6s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column h3.show {\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li a:hover {\r\n");
      out.write("	color: #32CD32;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons a:hover {\r\n");
      out.write("	color: #32CD32;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer-container\">\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Services</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li><a href=\"GetDoctorServlet?view=profiles\">Our Doctors</a></li>\r\n");
      out.write("				<li><a href=\"lab_test.jsp\">Lab Tests</a></li>\r\n");
      out.write("				<li><a href=\"Search.jsp\">Doctor Appointments</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Quick Links</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"about_us.jsp\">About Us</a></li>\r\n");
      out.write("				<li><a href=\"contactSupport.jsp\">Contact Us</a></li>\r\n");
      out.write("				<li><a href=\"feedback.jsp\">Feedback</a></li>\r\n");
      out.write("				<li><a href=\"health_tips.jsp\">Health Tips</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Online Information</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"TermsandConditions.jsp\">Terms and Conditions</a></li>\r\n");
      out.write("				<li><a href=\"privacy_policy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("				<li><a href=\"refunds.jsp\">Refunds</a></li>\r\n");
      out.write("				<li><a href=\"faq.jsp\">FAQ</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Find Us On</h3>\r\n");
      out.write("			<div class=\"social-icons\">\r\n");
      out.write("				<a href=\"https://www.facebook.com\"><img src=\"images/facebook_logo.webp\" alt=\"Facebook\" width=\"47px\"></a>\r\n");
      out.write("				<a href=\"https://www.whatsapp.com\"><img src=\"images/whatsapp-r.png\" alt=\"WhatsApp\" width=\"52px\"></a>\r\n");
      out.write("				<a href=\"https://www.twitter.com\"><img src=\"images/twitter_l.webp\" alt=\"Twitter\" width=\"52px\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<p>&copy; 2025 E-Channeling. All rights reserved.</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("    document.querySelectorAll('.footer-column h3').forEach(h => {\r\n");
      out.write("      h.classList.add('show');\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
