/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-06-10 07:32:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.Map;

public final class Search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1749535243280L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1749535243299L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Set character encoding to UTF-8 for proper text rendering -->\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Halomed | Search Doctors</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/halomed2.png\">\r\n");
      out.write("    <!-- Link to CSS files for styling -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/Search.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Import Poppins font from Google Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- JavaScript function to handle AJAX requests when dropdowns change -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function loadDoctors() {\r\n");
      out.write("            // Get values from dropdowns and date input\r\n");
      out.write("            var doctorname = document.getElementById(\"doctorname\").value;\r\n");
      out.write("            var specialization = document.getElementById(\"specialization\").value;\r\n");
      out.write("            var hospital = document.getElementById(\"hospital\").value;\r\n");
      out.write("            var date = document.getElementById(\"date\").value;\r\n");
      out.write("            \r\n");
      out.write("            // Only send AJAX request if at least one field is selected\r\n");
      out.write("            if (doctorname || specialization || hospital || date) {\r\n");
      out.write("                var xhr = new XMLHttpRequest();\r\n");
      out.write("                // Send GET request to SearchDoctorsServlet with encoded parameters\r\n");
      out.write("                xhr.open(\"GET\", \"SearchDoctorsServlet?doctorname=\" + encodeURIComponent(doctorname) + \r\n");
      out.write("                        \"&specialization=\" + encodeURIComponent(specialization) + \r\n");
      out.write("                        \"&hospital=\" + encodeURIComponent(hospital) + \r\n");
      out.write("                        \"&date=\" + encodeURIComponent(date), true);\r\n");
      out.write("                xhr.onreadystatechange = function() {\r\n");
      out.write("                    // Update the doctorList div with the response when ready\r\n");
      out.write("                    if (xhr.readyState == 4 && xhr.status == 200) {\r\n");
      out.write("                        document.getElementById(\"doctorList\").innerHTML = xhr.responseText;\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("                xhr.send();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // JavaScript function to handle delete confirmation\r\n");
      out.write("        function confirmDelete(form) {\r\n");
      out.write("            if (confirm(\"Are you sure you want to delete the appointment?\")) {\r\n");
      out.write("                form.submit(); // Submit the form if user clicks \"Yes\"\r\n");
      out.write("            }\r\n");
      out.write("            // If user clicks \"Cancel\", do nothing\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');

    String userType = (String) session.getAttribute("userType");
    Object sessionUser = session.getAttribute("user");
    String profileLink = "login.jsp";

    if (sessionUser != null && userType != null) {
        if ("patient".equals(userType)) {
            profileLink = "profile.jsp";
        } else if ("admin".equals(userType)) {
            profileLink = "adminDashboard.jsp";
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Header</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* Header Container */\r\n");
      out.write(".header {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 90px;\r\n");
      out.write("    background: linear-gradient(90deg, #FFDEE9, #B5FFFC);\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    padding: 0 40px;\r\n");
      out.write("    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    position: relative;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    transition: all 0.4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header:hover {\r\n");
      out.write("    background: linear-gradient(90deg, #B5FFFC, #FFDEE9);\r\n");
      out.write("    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Logo Section */\r\n");
      out.write(".logo_box img {\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    max-width: 200px;\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo_box img:hover {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navigation Section */\r\n");
      out.write(".nav_bar {\r\n");
      out.write("    flex-grow: 1;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a {\r\n");
      out.write("    color: #333;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    padding: 10px 18px;\r\n");
      out.write("    transition: background-color 0.3s, transform 0.3s;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a:hover {\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.4);\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Profile Icon */\r\n");
      out.write(".user-cart {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons a img {\r\n");
      out.write("    width: 55px;\r\n");
      out.write("    height: 55px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    transition: box-shadow 0.3s ease, transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icons a:hover img {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("    box-shadow: 0 0 10px rgba(255, 255, 255, 0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Animated Underline Effect */\r\n");
      out.write(".nav_links a::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background: #333;\r\n");
      out.write("    transition: width 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_links a:hover::after {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"logo_box\">\r\n");
      out.write("        <img src=\"images/logo3.png\" alt=\"Logo\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"nav_bar\">\r\n");
      out.write("        <div class=\"nav_links\">\r\n");
      out.write("            <a href=\"index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"GetDoctorServlet?view=profiles\">Doctors</a>\r\n");
      out.write("            <a href=\"Search.jsp\">Appointment</a>\r\n");
      out.write("            <a href=\"lab_test.jsp\">Lab Test</a>\r\n");
      out.write("            <a href=\"contactSupport.jsp\">Contact Us</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"user-cart\">\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <a href=\"");
      out.print( profileLink );
      out.write("\">\r\n");
      out.write("                <img src=\"images/user-r.png\" alt=\"Profile\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div class=\"relative min-h-screen bg-cover bg-center\" style=\"background-image: url(images/newSearch.jpeg); background-repeat: no-repeat; background-size: cover; min-height: 100vh;\">\r\n");
      out.write("    ");
 String status = (String) request.getAttribute("status"); 
      out.write("\r\n");
      out.write("    ");
 if (status != null) { 
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            setTimeout(function () {\r\n");
      out.write("                alert(\"");
      out.print( status );
      out.write("\");\r\n");
      out.write("            }, 1000);\r\n");
      out.write("        </script>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"search-container\">\r\n");
      out.write("        <form action=\"SearchDoctorsServlet\" method=\"post\">\r\n");
      out.write("            <label for=\"doctorname\">Doctor Name:</label>\r\n");
      out.write("            <select id=\"doctorname\" name=\"doctorname\" onchange=\"loadDoctors()\">\r\n");
      out.write("                <option value=\"\">Select Doctor</option>\r\n");
      out.write("                <option value=\"M.Charith Wijesinghe\">M.Charith Wijesinghe</option>\r\n");
      out.write("                <option value=\"W.Thusil Wanninayaka\">W.Thusil Wanninayaka</option>\r\n");
      out.write("                <option value=\"J.Jagath Pathirana\">J.Jagath Pathirana</option>\r\n");
      out.write("                <option value=\"N.Ashoka Subasinghe\">N.Ashoka Subasinghe</option>\r\n");
      out.write("                <option value=\"R.Vimarsha Hemamali\">R.Vimarsha Hemamali</option>\r\n");
      out.write("                <option value=\"P.Thusitha Gunawardena\">P.Thusitha Gunawardena</option>\r\n");
      out.write("                <option value=\"K.Jayoda Sadagoda\">K.Jayoda Sadagoda</option>\r\n");
      out.write("                <option value=\"C.Hasini Ishuwara\">C.Hasini Ishuwara</option>\r\n");
      out.write("                <option value=\"A.Akmal Azam\">A.Akmal Azam</option>\r\n");
      out.write("                <option value=\"Y.Yapa Jayasinghe\">Y.Yapa Jayasinghe</option>\r\n");
      out.write("                <option value=\"K.Ashok Selvanagavan\">K.Ashok Selvanagavan</option>\r\n");
      out.write("                <option value=\"P.Lewis Hamilton\">P.Lewis Hamilton</option>\r\n");
      out.write("                <option value=\"L.Charles Leclerc\">L.Charles Leclerc</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            \r\n");
      out.write("            <label for=\"specialization\">Specialization:</label>\r\n");
      out.write("            <select id=\"specialization\" name=\"specialization\" onchange=\"loadDoctors()\">\r\n");
      out.write("                <option value=\"\">Select Specialization</option>\r\n");
      out.write("                <option value=\"General Practitioner\">General Practitioner</option>\r\n");
      out.write("                <option value=\"Cardiologist\">Cardiologist</option>\r\n");
      out.write("                <option value=\"Dermatologist\">Dermatologist</option>\r\n");
      out.write("                <option value=\"Neurologist\">Neurologist</option>\r\n");
      out.write("                <option value=\"Psychiatrist\">Psychiatrist</option>\r\n");
      out.write("                <option value=\"Dentist\">Dentist</option>\r\n");
      out.write("                <option value=\"ENT Specialist\">ENT Specialist</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"hospital\">Hospital:</label>\r\n");
      out.write("            <select id=\"hospital\" name=\"hospital\" onchange=\"loadDoctors()\">\r\n");
      out.write("                <option value=\"\">Select Hospital</option>\r\n");
      out.write("                <option value=\"City Hospital\">City Hospital</option>\r\n");
      out.write("                <option value=\"Town Clinic\">Town Clinic</option>\r\n");
      out.write("                <option value=\"Nawinna Hospital\">Nawinna Hospital</option>\r\n");
      out.write("                <option value=\"CO-OP Hospital\">CO-OP Hospital</option>\r\n");
      out.write("                <option value=\"SethSevana Hospital\">SethSevana Hospital</option>\r\n");
      out.write("                <option value=\"Med Clinic\">Med Clinic</option>\r\n");
      out.write("            </select>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"date\">Date:</label>\r\n");
      out.write("            <input type=\"date\" id=\"date\" name=\"date\" onchange=\"loadDoctors()\" />\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"doctorList\">\r\n");
      out.write("        ");
 
        List<Map<String, String>> doctors = (List<Map<String, String>>) request.getAttribute("doctors");
        //  out.println("Debug: Number of doctors = " + (doctors != null ? doctors.size() : "null") + "<br>");
        if (doctors != null && !doctors.isEmpty()) {
            for (Map<String, String> doctor : doctors) { 
        
      out.write("\r\n");
      out.write("                <div class=\"doctor-result\">\r\n");
      out.write("                    <div class=\"doctor-info\">\r\n");
      out.write("      \r\n");
      out.write("                        <div class=\"details\">\r\n");
      out.write("                            <p>");
      out.print( doctor.get("hospital") != null ? doctor.get("hospital") : "" );
      out.write("</p>\r\n");
      out.write("                            <p>");
      out.print( doctor.get("specialization") != null ? doctor.get("specialization") : "" );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"time\">\r\n");
      out.write("                        <p>");
      out.print( doctor.get("time") != null ? doctor.get("time") : "" );
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"patients\">\r\n");
      out.write("                        <p>0 Patients</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fee\">\r\n");
      out.write("                        <p>Rs 4,500.00 + Channelling Fee</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"Index1.jsp?doctorName=");
      out.print( java.net.URLEncoder.encode(doctor.get("name") != null ? doctor.get("name") : "", "UTF-8") );
      out.write("&specialization=");
      out.print( java.net.URLEncoder.encode(doctor.get("specialization") != null ? doctor.get("specialization") : "", "UTF-8") );
      out.write("&hospital=");
      out.print( java.net.URLEncoder.encode(doctor.get("hospital") != null ? doctor.get("hospital") : "", "UTF-8") );
      out.write("&date=");
      out.print( java.net.URLEncoder.encode(doctor.get("date") != null ? doctor.get("date") : "", "UTF-8") );
      out.write("&time=");
      out.print( java.net.URLEncoder.encode(doctor.get("time") != null ? doctor.get("time") : "", "UTF-8") );
      out.write("\">\r\n");
      out.write("                        <button type=\"button\" class=\"book-btn\">Make Appointment</button>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p style=\"text-align: center; font-weight: 600; color: #1976d2;\">");
      out.print( doctor.get("date") != null ? doctor.get("date") : "" );
      out.write("</p>\r\n");
      out.write("        ");
 
            }
        } else if (request.getAttribute("doctors") != null) {
        
      out.write("\r\n");
      out.write("        <div class=\"error-container\">\r\n");
      out.write("            <p class=\"error\">No doctors available for the selected criteria.</p>\r\n");
      out.write("         </div>\r\n");
      out.write("        ");

        } 
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"appointment-details\">\r\n");
      out.write("        <h3>Appointment Summary</h3>\r\n");
      out.write("        ");
 
        String doctorName = (String) request.getAttribute("doctorName");
        if (doctorName != null) { 
        
      out.write("\r\n");
      out.write("            <p><strong>Booking ID:</strong> ");
      out.print( request.getAttribute("bookingID") );
      out.write("</p>\r\n");
      out.write("            <p><strong>Doctor Name:</strong> ");
      out.print( request.getAttribute("doctorName") );
      out.write("</p>\r\n");
      out.write("            <p><strong>Specialization:</strong> ");
      out.print( request.getAttribute("specialization") );
      out.write("</p>\r\n");
      out.write("            <p><strong>Hospital:</strong> ");
      out.print( request.getAttribute("hospital") );
      out.write("</p>\r\n");
      out.write("            <p><strong>Date:</strong> ");
      out.print( request.getAttribute("date") );
      out.write("</p>\r\n");
      out.write("            <p><strong>Time:</strong> ");
      out.print( request.getAttribute("time") );
      out.write("</p>\r\n");
      out.write("            <p><strong>Patient Name:</strong> ");
      out.print( request.getAttribute("name") != null ? request.getAttribute("name") : "N/A" );
      out.write("</p>\r\n");
      out.write("            <p><strong>Age:</strong> ");
      out.print( request.getAttribute("age") != null ? request.getAttribute("age") : "N/A" );
      out.write("</p>\r\n");
      out.write("            <p><strong>Gender:</strong> ");
      out.print( request.getAttribute("gender") != null ? request.getAttribute("gender") : "N/A" );
      out.write("</p>\r\n");
      out.write("            <p><strong>Email:</strong> ");
      out.print( request.getAttribute("email") != null ? request.getAttribute("email") : "N/A" );
      out.write("</p>\r\n");
      out.write("            <p><strong>Phone:</strong> ");
      out.print( request.getAttribute("phone") != null ? request.getAttribute("phone") : "N/A" );
      out.write("</p>\r\n");
      out.write("     \r\n");
      out.write("            <form id=\"deleteAppointmentForm\" action=\"DeleteAppointmentServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"bookingID\" value=\"");
      out.print( request.getAttribute("bookingID") );
      out.write("\">\r\n");
      out.write("                <button type=\"button\" class=\"delete-btn\" onclick=\"confirmDelete(this.form)\">Delete Appointment</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <p>No appointment selected</p>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("footer {\r\n");
      out.write("	background: #0096c7;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 30px 0;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column h3 {\r\n");
      out.write("	color: white;\r\n");
      out.write("	border-bottom: 2px solid #32CD32;\r\n");
      out.write("	padding-bottom: 5px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	transform: translateY(30px);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	transition: transform 0.6s ease-out, opacity 0.6s ease-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column h3.show {\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer-column ul li a:hover {\r\n");
      out.write("	color: #32CD32;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	gap: 10px;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	transition: color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".social-icons a:hover {\r\n");
      out.write("	color: #32CD32;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer-container\">\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Services</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("				<li><a href=\"GetDoctorServlet?view=profiles\">Our Doctors</a></li>\r\n");
      out.write("				<li><a href=\"lab_test.jsp\">Lab Tests</a></li>\r\n");
      out.write("				<li><a href=\"Search.jsp\">Doctor Appointments</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Quick Links</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"about_us.jsp\">About Us</a></li>\r\n");
      out.write("				<li><a href=\"contactSupport.jsp\">Contact Us</a></li>\r\n");
      out.write("				<li><a href=\"feedback.jsp\">Feedback</a></li>\r\n");
      out.write("				<li><a href=\"health_tips.jsp\">Health Tips</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Online Information</h3>\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"TermsandConditions.jsp\">Terms and Conditions</a></li>\r\n");
      out.write("				<li><a href=\"privacy_policy.jsp\">Privacy Policy</a></li>\r\n");
      out.write("				<li><a href=\"refunds.jsp\">Refunds</a></li>\r\n");
      out.write("				<li><a href=\"faq.jsp\">FAQ</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"footer-column\">\r\n");
      out.write("			<h3>Find Us On</h3>\r\n");
      out.write("			<div class=\"social-icons\">\r\n");
      out.write("				<a href=\"https://www.facebook.com\"><img src=\"images/facebook_logo.webp\" alt=\"Facebook\" width=\"47px\"></a>\r\n");
      out.write("				<a href=\"https://www.whatsapp.com\"><img src=\"images/whatsapp-r.png\" alt=\"WhatsApp\" width=\"52px\"></a>\r\n");
      out.write("				<a href=\"https://www.twitter.com\"><img src=\"images/twitter_l.webp\" alt=\"Twitter\" width=\"52px\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<p>&copy; 2025 E-Channeling. All rights reserved.</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("    document.querySelectorAll('.footer-column h3').forEach(h => {\r\n");
      out.write("      h.classList.add('show');\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
