/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-05-19 07:12:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateAvailability_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>HaloMed | Update Availability</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/halomed2.png\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/updateAvailability.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h1>Update Availability</h1>\r\n");
      out.write("    ");

 		// Get values from request parameters
        String availability_id = request.getParameter("availability_id");
        String hospital_name = request.getParameter("hospital_name");
        String location = request.getParameter("location");
        String day = request.getParameter("day"); // Comes as "Mon", "Tue", etc.
        String time = request.getParameter("time");
        String max_patients = request.getParameter("max_patients");
        String fee = request.getParameter("fee");
        
        //formatted date
        String formattedTime = time != null ? time : "";
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("	<!-- Form to submit updated availability details -->\r\n");
      out.write("    <form action=\"UpdateAvailabilityServlet\" method=\"post\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Availability ID:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"availability_id\" value=\"");
      out.print(availability_id);
      out.write("\" readonly></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("			    <td>Hospital Name:</td>\r\n");
      out.write("			    <td>\r\n");
      out.write("			        <input list=\"hospitalList\" name=\"hospital_name\" value=\"");
      out.print(hospital_name);
      out.write("\" required style=\"width: 100%; padding: 8px; border: 1px solid #ccc; border-radius: 4px;\">\r\n");
      out.write("			        <datalist id=\"hospitalList\">\r\n");
      out.write("			            <option value=\"Asiri\">\r\n");
      out.write("						<option value=\"Nawaloka\">\r\n");
      out.write("						<option value=\"Lanka Hospitals\">\r\n");
      out.write("						<option value=\"Hemas\">\r\n");
      out.write("						<option value=\"Durdans\">\r\n");
      out.write("						<option value=\"Seth Sevana Hospitals\">\r\n");
      out.write("						<option value=\"Cooperative Hospital\">\r\n");
      out.write("						<option value=\"Navinne\">\r\n");
      out.write("						<option value=\"Ninewells\">\r\n");
      out.write("						<option value=\"Kings Hospital\">\r\n");
      out.write("			        </datalist>\r\n");
      out.write("			    </td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Location:</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"location\" value=\"");
      out.print(location);
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Day:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select name=\"day\" required>\r\n");
      out.write("                        <option value=\"Mon\" ");
      out.print( "Mon".equals(day) ? "selected" : "" );
      out.write(">Monday</option>\r\n");
      out.write("                        <option value=\"Tue\" ");
      out.print( "Tue".equals(day) ? "selected" : "" );
      out.write(">Tuesday</option>\r\n");
      out.write("                        <option value=\"Wed\" ");
      out.print( "Wed".equals(day) ? "selected" : "" );
      out.write(">Wednesday</option>\r\n");
      out.write("                        <option value=\"Thu\" ");
      out.print( "Thu".equals(day) ? "selected" : "" );
      out.write(">Thursday</option>\r\n");
      out.write("                        <option value=\"Fri\" ");
      out.print( "Fri".equals(day) ? "selected" : "" );
      out.write(">Friday</option>\r\n");
      out.write("                        <option value=\"Sat\" ");
      out.print( "Sat".equals(day) ? "selected" : "" );
      out.write(">Saturday</option>\r\n");
      out.write("                        <option value=\"Sun\" ");
      out.print( "Sun".equals(day) ? "selected" : "" );
      out.write(">Sunday</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Time:</td>\r\n");
      out.write("                <td><input type=\"datetime-local\" name=\"time\" value=\"");
      out.print(formattedTime);
      out.write("\" step=\"1\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Max Patients:</td>\r\n");
      out.write("                <td><input type=\"number\" name=\"max_patients\" value=\"");
      out.print(max_patients);
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Fee (Rs):</td>\r\n");
      out.write("                <td><input type=\"number\" step=\"0.01\" name=\"fee\" value=\"");
      out.print(fee);
      out.write("\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\"><input type=\"submit\" value=\"Submit\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
